title: dsrmie.github.io
description: Just a blog here.
template:
  repo: dsrmie.github.io-template
  name: dsrmie.github.io
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
